part of 'icon_constant.dart';

const IconCategoryModel _$alienCategoryIcons = IconCategoryModel(
  display: 'alien',
  path: AlienConstant.categoryIcon,
  position: AlienConstant.categoryNo,
  icons: [
    IconModel(display: 'alien01Icon', path: AlienConstant.alien01Icon),
    IconModel(display: 'alien02Icon', path: AlienConstant.alien02Icon),
    IconModel(display: 'alien03Icon', path: AlienConstant.alien03Icon),
    IconModel(display: 'alien04Icon', path: AlienConstant.alien04Icon),
    IconModel(display: 'alien05Icon', path: AlienConstant.alien05Icon),
    IconModel(display: 'alien06Icon', path: AlienConstant.alien06Icon),
    IconModel(display: 'alien07Icon', path: AlienConstant.alien07Icon),
    IconModel(display: 'alien08Icon', path: AlienConstant.alien08Icon),
    IconModel(display: 'alien09Icon', path: AlienConstant.alien09Icon),
    IconModel(display: 'alien10Icon', path: AlienConstant.alien10Icon),
    IconModel(display: 'alien8Icon', path: AlienConstant.alien8Icon),
    IconModel(display: 'planet01Icon', path: AlienConstant.planet01Icon),
    IconModel(display: 'planet02Icon', path: AlienConstant.planet02Icon),
    IconModel(display: 'planet03Icon', path: AlienConstant.planet03Icon),
    IconModel(display: 'planet04Icon', path: AlienConstant.planet04Icon),
    IconModel(display: 'planet05Icon', path: AlienConstant.planet05Icon),
    IconModel(display: 'planet06Icon', path: AlienConstant.planet06Icon),
    IconModel(display: 'planet07Icon', path: AlienConstant.planet07Icon),
    IconModel(display: 'planet08Icon', path: AlienConstant.planet08Icon),
    IconModel(display: 'planet09Icon', path: AlienConstant.planet09Icon),
    IconModel(display: 'planet10Icon', path: AlienConstant.planet10Icon),
    IconModel(display: 'planet11Icon', path: AlienConstant.planet11Icon),
    IconModel(display: 'planet12Icon', path: AlienConstant.planet12Icon),
    IconModel(display: 'planet13Icon', path: AlienConstant.planet13Icon),
    IconModel(display: 'planet14Icon', path: AlienConstant.planet14Icon),
    IconModel(display: 'ufo01Icon', path: AlienConstant.ufo01Icon),
    IconModel(display: 'ufo02Icon', path: AlienConstant.ufo02Icon),
    IconModel(display: 'ufo03Icon', path: AlienConstant.ufo03Icon),
    IconModel(display: 'weaponIcon', path: AlienConstant.weaponIcon),
    IconModel(display: 'zodiacIcon', path: AlienConstant.zodiacIcon),
  ],
);
