part of 'icon_constant.dart';

const IconCategoryModel _$animalCategoryIcons = IconCategoryModel(
  display: 'animal',
  path: AnimalConstant.categoryIcon,
  position: AnimalConstant.categoryNo,
  icons: [
      IconModel(display: 'animal01Icon', path: AnimalConstant.animal01Icon),
      IconModel(display: 'animal02Icon', path: AnimalConstant.animal02Icon),
      IconModel(display: 'animal03Icon', path: AnimalConstant.animal03Icon),
      IconModel(display: 'animal04Icon', path: AnimalConstant.animal04Icon),
      IconModel(display: 'animal05Icon', path: AnimalConstant.animal05Icon),
      IconModel(display: 'animal06Icon', path: AnimalConstant.animal06Icon),
      IconModel(display: 'animal07Icon', path: AnimalConstant.animal07Icon),
      IconModel(display: 'animal07bIcon', path: AnimalConstant.animal07bIcon),
      IconModel(display: 'animal08Icon', path: AnimalConstant.animal08Icon),
      IconModel(display: 'animal09Icon', path: AnimalConstant.animal09Icon),
      IconModel(display: 'animal10Icon', path: AnimalConstant.animal10Icon),
      IconModel(display: 'animal10bIcon', path: AnimalConstant.animal10bIcon),
      IconModel(display: 'animal11Icon', path: AnimalConstant.animal11Icon),
      IconModel(display: 'animal11cIcon', path: AnimalConstant.animal11cIcon),
      IconModel(display: 'animal12Icon', path: AnimalConstant.animal12Icon),
      IconModel(display: 'animal13Icon', path: AnimalConstant.animal13Icon),
      IconModel(display: 'animal14Icon', path: AnimalConstant.animal14Icon),
      IconModel(display: 'animal15Icon', path: AnimalConstant.animal15Icon),
      IconModel(display: 'animal16Icon', path: AnimalConstant.animal16Icon),
      IconModel(display: 'beeIcon', path: AnimalConstant.beeIcon),
      IconModel(display: 'beehiveIcon', path: AnimalConstant.beehiveIcon),
      IconModel(display: 'butterflyIcon', path: AnimalConstant.butterflyIcon),
      IconModel(display: 'dolphinIcon', path: AnimalConstant.dolphinIcon),
      IconModel(display: 'dolphin2Icon', path: AnimalConstant.dolphin2Icon),
      IconModel(display: 'fishIcon', path: AnimalConstant.fishIcon),
      IconModel(display: 'fishbIcon', path: AnimalConstant.fishbIcon),
      IconModel(display: 'lobsterIcon', path: AnimalConstant.lobsterIcon),
      IconModel(display: 'sealIcon', path: AnimalConstant.sealIcon),
      IconModel(display: 'snailIcon', path: AnimalConstant.snailIcon),
      IconModel(display: 'snakeIcon', path: AnimalConstant.snakeIcon),
      IconModel(display: 'symbol01Icon', path: AnimalConstant.symbol01Icon),
      IconModel(display: 'symbol02Icon', path: AnimalConstant.symbol02Icon),
      IconModel(display: 'symbol03Icon', path: AnimalConstant.symbol03Icon),
      IconModel(display: 'symbol04Icon', path: AnimalConstant.symbol04Icon),
      IconModel(display: 'symbol05Icon', path: AnimalConstant.symbol05Icon),
      IconModel(display: 'symbol07Icon', path: AnimalConstant.symbol07Icon),
      IconModel(display: 'waspIcon', path: AnimalConstant.waspIcon),
      IconModel(display: 'whaleIcon', path: AnimalConstant.whaleIcon),
  ]
);
