part of 'icon_constant.dart';

const IconCategoryModel _$bulltesCategoryIcons = IconCategoryModel(
  display: 'bullets',
  path: BulletsConstant.categoryIcon,
  position: BulletsConstant.categoryNo,
  icons: [
    IconModel(display: 'abullet02Icon', path: BulletsConstant.abullet02Icon),
    IconModel(display: 'abullet02bIcon', path: BulletsConstant.abullet02bIcon),
    IconModel(display: 'abullet03Icon', path: BulletsConstant.abullet03Icon),
    IconModel(display: 'abullet03bIcon', path: BulletsConstant.abullet03bIcon),
    IconModel(display: 'abullet04Icon', path: BulletsConstant.abullet04Icon),
    IconModel(display: 'abullet05Icon', path: BulletsConstant.abullet05Icon),
    IconModel(display: 'abullet06Icon', path: BulletsConstant.abullet06Icon),
    IconModel(display: 'abullet07Icon', path: BulletsConstant.abullet07Icon),
    IconModel(display: 'abullet08Icon', path: BulletsConstant.abullet08Icon),
    IconModel(display: 'abullet09Icon', path: BulletsConstant.abullet09Icon),
    IconModel(display: 'abullet10Icon', path: BulletsConstant.abullet10Icon),
    IconModel(display: 'abullet11Icon', path: BulletsConstant.abullet11Icon),
    IconModel(display: 'abullet11bIcon', path: BulletsConstant.abullet11bIcon),
    IconModel(display: 'abullet12Icon', path: BulletsConstant.abullet12Icon),
    IconModel(display: 'number0Icon', path: BulletsConstant.number0Icon),
    IconModel(display: 'number00Icon', path: BulletsConstant.number00Icon),
    IconModel(display: 'number01Icon', path: BulletsConstant.number01Icon),
    IconModel(display: 'number02Icon', path: BulletsConstant.number02Icon),
    IconModel(display: 'number03Icon', path: BulletsConstant.number03Icon),
    IconModel(display: 'number04Icon', path: BulletsConstant.number04Icon),
    IconModel(display: 'number05Icon', path: BulletsConstant.number05Icon),
    IconModel(display: 'number06Icon', path: BulletsConstant.number06Icon),
    IconModel(display: 'number07Icon', path: BulletsConstant.number07Icon),
    IconModel(display: 'number08Icon', path: BulletsConstant.number08Icon),
    IconModel(display: 'number09Icon', path: BulletsConstant.number09Icon),
    IconModel(display: 'number10Icon', path: BulletsConstant.number10Icon),
    IconModel(display: 'number11Icon', path: BulletsConstant.number11Icon),
    IconModel(display: 'number12Icon', path: BulletsConstant.number12Icon),
    IconModel(display: 'number123Icon', path: BulletsConstant.number123Icon),
    IconModel(display: 'number13Icon', path: BulletsConstant.number13Icon),
    IconModel(display: 'number14Icon', path: BulletsConstant.number14Icon),
    IconModel(display: 'number15Icon', path: BulletsConstant.number15Icon),
    IconModel(display: 'z01Icon', path: BulletsConstant.z01Icon),
    IconModel(display: 'z02Icon', path: BulletsConstant.z02Icon),
    IconModel(display: 'z03Icon', path: BulletsConstant.z03Icon),
    IconModel(display: 'z04Icon', path: BulletsConstant.z04Icon),
    IconModel(display: 'z05Icon', path: BulletsConstant.z05Icon),
    IconModel(display: 'z06Icon', path: BulletsConstant.z06Icon),
    IconModel(display: 'z07Icon', path: BulletsConstant.z07Icon),
    IconModel(display: 'z08Icon', path: BulletsConstant.z08Icon),
    IconModel(display: 'z09Icon', path: BulletsConstant.z09Icon),
    IconModel(display: 'z10Icon', path: BulletsConstant.z10Icon),
    IconModel(display: 'z11Icon', path: BulletsConstant.z11Icon),
    IconModel(display: 'z12Icon', path: BulletsConstant.z12Icon),
    IconModel(display: 'z13Icon', path: BulletsConstant.z13Icon),
    IconModel(display: 'z14Icon', path: BulletsConstant.z14Icon),
    IconModel(display: 'z15Icon', path: BulletsConstant.z15Icon),
    IconModel(display: 'z16Icon', path: BulletsConstant.z16Icon),
    IconModel(display: 'z17Icon', path: BulletsConstant.z17Icon),
    IconModel(display: 'z18Icon', path: BulletsConstant.z18Icon),
    IconModel(display: 'z19Icon', path: BulletsConstant.z19Icon),
    IconModel(display: 'z20Icon', path: BulletsConstant.z20Icon),
    IconModel(display: 'z21Icon', path: BulletsConstant.z21Icon),
    IconModel(display: 'z22Icon', path: BulletsConstant.z22Icon),
    IconModel(display: 'z31Icon', path: BulletsConstant.z31Icon),
    IconModel(display: 'z32Icon', path: BulletsConstant.z32Icon),
    IconModel(display: 'z33Icon', path: BulletsConstant.z33Icon),
    IconModel(display: 'z34Icon', path: BulletsConstant.z34Icon),
    IconModel(display: 'z35Icon', path: BulletsConstant.z35Icon),
    IconModel(display: 'z36Icon', path: BulletsConstant.z36Icon),
    IconModel(display: 'z37Icon', path: BulletsConstant.z37Icon),
    IconModel(display: 'z38Icon', path: BulletsConstant.z38Icon),
  ],
);
