part of 'icon_constant.dart';

const IconCategoryModel _$chemistryCategoryIcons = IconCategoryModel(
  display: 'chemistry',
  path: ChemistryConstant.categoryIcon,
  position: ChemistryConstant.categoryNo,
  icons: [
    IconModel(display: 'che0Icon', path: ChemistryConstant.che0Icon),
    IconModel(display: 'chemistry01Icon', path: ChemistryConstant.chemistry01Icon),
    IconModel(display: 'chemistry011Icon', path: ChemistryConstant.chemistry011Icon),
    IconModel(display: 'chemistry012Icon', path: ChemistryConstant.chemistry012Icon),
    IconModel(display: 'chemistry02Icon', path: ChemistryConstant.chemistry02Icon),
    IconModel(display: 'chemistry03Icon', path: ChemistryConstant.chemistry03Icon),
    IconModel(display: 'chemistry04Icon', path: ChemistryConstant.chemistry04Icon),
    IconModel(display: 'chemistry05Icon', path: ChemistryConstant.chemistry05Icon),
    IconModel(display: 'chemistry06Icon', path: ChemistryConstant.chemistry06Icon),
    IconModel(display: 'chemistry07Icon', path: ChemistryConstant.chemistry07Icon),
    IconModel(display: 'chemistry08Icon', path: ChemistryConstant.chemistry08Icon),
    IconModel(display: 'chemistry09Icon', path: ChemistryConstant.chemistry09Icon),
    IconModel(display: 'chemistry10Icon', path: ChemistryConstant.chemistry10Icon),
    IconModel(display: 'chemistry13Icon', path: ChemistryConstant.chemistry13Icon),
    IconModel(display: 'chemistry14Icon', path: ChemistryConstant.chemistry14Icon),
    IconModel(display: 'flask3Icon', path: ChemistryConstant.flask3Icon),
    IconModel(display: 'flask4Icon', path: ChemistryConstant.flask4Icon),
    IconModel(display: 'flask5Icon', path: ChemistryConstant.flask5Icon),
    IconModel(display: 'goldIcon', path: ChemistryConstant.goldIcon),
    IconModel(display: 'gold2Icon', path: ChemistryConstant.gold2Icon),
    IconModel(display: 'ironIcon', path: ChemistryConstant.ironIcon),
    IconModel(display: 'leadIcon', path: ChemistryConstant.leadIcon),
    IconModel(display: 'lead2Icon', path: ChemistryConstant.lead2Icon),
    IconModel(display: 'magnesiumIcon', path: ChemistryConstant.magnesiumIcon),
    IconModel(display: 'mercuryIcon', path: ChemistryConstant.mercuryIcon),
    IconModel(display: 'oxygen2Icon', path: ChemistryConstant.oxygen2Icon),
    IconModel(display: 'platinumIcon', path: ChemistryConstant.platinumIcon),
    IconModel(display: 's01Icon', path: ChemistryConstant.s01Icon),
    IconModel(display: 'silverIcon', path: ChemistryConstant.silverIcon),
    IconModel(display: 'sodiumIcon', path: ChemistryConstant.sodiumIcon),
    IconModel(display: 'v01Icon', path: ChemistryConstant.v01Icon),
    IconModel(display: 'v02Icon', path: ChemistryConstant.v02Icon),
  ],
);
