part of 'icon_constant.dart';

const IconCategoryModel _$egyptCategoryIcons = IconCategoryModel(
  display: 'egypt',
  path: EgyptConstant.categoryIcon,
  position: EgyptConstant.categoryNo,
  icons: [
    IconModel(display: 'ancientscrollIcon', path: EgyptConstant.ancientscrollIcon),
    IconModel(display: 'ankhIcon', path: EgyptConstant.ankhIcon),
    IconModel(display: 'anubisIcon', path: EgyptConstant.anubisIcon),
    IconModel(display: 'anubis2Icon', path: EgyptConstant.anubis2Icon),
    IconModel(display: 'beetleIcon', path: EgyptConstant.beetleIcon),
    IconModel(display: 'beetle2Icon', path: EgyptConstant.beetle2Icon),
    IconModel(display: 'cartoucheIcon', path: EgyptConstant.cartoucheIcon),
    IconModel(display: 'catIcon', path: EgyptConstant.catIcon),
    IconModel(display: 'cleopatraIcon', path: EgyptConstant.cleopatraIcon),
    IconModel(display: 'columnIcon', path: EgyptConstant.columnIcon),
    IconModel(display: 'crookIcon', path: EgyptConstant.crookIcon),
    IconModel(display: 'eagleIcon', path: EgyptConstant.eagleIcon),
    IconModel(display: 'egypt2Icon', path: EgyptConstant.egypt2Icon),
    IconModel(display: 'eyeofraIcon', path: EgyptConstant.eyeofraIcon),
    IconModel(display: 'flowerIcon', path: EgyptConstant.flowerIcon),
    IconModel(display: 'greatsphinxofgizaIcon', path: EgyptConstant.greatsphinxofgizaIcon),
    IconModel(display: 'hieroglyphIcon', path: EgyptConstant.hieroglyphIcon),
    IconModel(display: 'hieroglyph2Icon', path: EgyptConstant.hieroglyph2Icon),
    IconModel(display: 'hieroglyph3Icon', path: EgyptConstant.hieroglyph3Icon),
    IconModel(display: 'mummyIcon', path: EgyptConstant.mummyIcon),
    IconModel(display: 'pharaohIcon', path: EgyptConstant.pharaohIcon),
    IconModel(display: 'pyramids02Icon', path: EgyptConstant.pyramids02Icon),
    IconModel(display: 'pyramids03Icon', path: EgyptConstant.pyramids03Icon),
    IconModel(display: 'pyramids04Icon', path: EgyptConstant.pyramids04Icon),
    IconModel(display: 'pyramids06Icon', path: EgyptConstant.pyramids06Icon),
    IconModel(display: 'pyramids07Icon', path: EgyptConstant.pyramids07Icon),
    IconModel(display: 'scorpionIcon', path: EgyptConstant.scorpionIcon),
    IconModel(display: 'sphinxIcon', path: EgyptConstant.sphinxIcon),
    IconModel(display: 'sphinx2Icon', path: EgyptConstant.sphinx2Icon),
    IconModel(display: 'thothIcon', path: EgyptConstant.thothIcon),
  ],
);
