
part of 'icon_constant.dart';

const IconCategoryModel _$humanCategoryIcons = IconCategoryModel(
  display: 'human',
  path: HumanConstant.categoryIcon,
  position: HumanConstant.categoryNo,
  icons: [
    IconModel(display: 'arteryIcon', path: HumanConstant.arteryIcon),
    IconModel(display: 'bone003Icon', path: HumanConstant.bone003Icon),
    IconModel(display: 'bone01Icon', path: HumanConstant.bone01Icon),
    IconModel(display: 'bone02Icon', path: HumanConstant.bone02Icon),
    IconModel(display: 'bone04Icon', path: HumanConstant.bone04Icon),
    IconModel(display: 'bone05Icon', path: HumanConstant.bone05Icon),
    IconModel(display: 'epidermisIcon', path: HumanConstant.epidermisIcon),
    IconModel(display: 'humanresourcesIcon', path: HumanConstant.humanresourcesIcon),
    IconModel(display: 'human009Icon', path: HumanConstant.human009Icon),
    IconModel(display: 'human01Icon', path: HumanConstant.human01Icon),
    IconModel(display: 'human02Icon', path: HumanConstant.human02Icon),
    IconModel(display: 'human03Icon', path: HumanConstant.human03Icon),
    IconModel(display: 'human04Icon', path: HumanConstant.human04Icon),
    IconModel(display: 'human05Icon', path: HumanConstant.human05Icon),
    IconModel(display: 'human06Icon', path: HumanConstant.human06Icon),
    IconModel(display: 'human07Icon', path: HumanConstant.human07Icon),
    IconModel(display: 'human08Icon', path: HumanConstant.human08Icon),
    IconModel(display: 'human10Icon', path: HumanConstant.human10Icon),
    IconModel(display: 'human12Icon', path: HumanConstant.human12Icon),
    IconModel(display: 'musclesIcon', path: HumanConstant.musclesIcon),
    IconModel(display: 'neuronIcon', path: HumanConstant.neuronIcon),
    IconModel(display: 'noseIcon', path: HumanConstant.noseIcon),
    IconModel(display: 'orgIcon', path: HumanConstant.orgIcon),
    IconModel(display: 'org0Icon', path: HumanConstant.org0Icon),
    IconModel(display: 'org005Icon', path: HumanConstant.org005Icon),
    IconModel(display: 'org005bIcon', path: HumanConstant.org005bIcon),
    IconModel(display: 'org006Icon', path: HumanConstant.org006Icon),
    IconModel(display: 'org007Icon', path: HumanConstant.org007Icon),
    IconModel(display: 'org008Icon', path: HumanConstant.org008Icon),
    IconModel(display: 'org009Icon', path: HumanConstant.org009Icon),
    IconModel(display: 'org01Icon', path: HumanConstant.org01Icon),
    IconModel(display: 'org02Icon', path: HumanConstant.org02Icon),
    IconModel(display: 'org03Icon', path: HumanConstant.org03Icon),
    IconModel(display: 'org04Icon', path: HumanConstant.org04Icon),
    IconModel(display: 'physiologyIcon', path: HumanConstant.physiologyIcon),
    IconModel(display: 'redbloodcellsIcon', path: HumanConstant.redbloodcellsIcon),
    IconModel(display: 'ribcageIcon', path: HumanConstant.ribcageIcon),
    IconModel(display: 'skeletonIcon', path: HumanConstant.skeletonIcon),
    IconModel(display: 'spineIcon', path: HumanConstant.spineIcon),
  ],
);