part of 'icon_constant.dart';

const IconCategoryModel _$moneyCategoryIcons = IconCategoryModel(
  display: 'money',
  path: MoneyConstant.categoryIcon,
  position: MoneyConstant.categoryNo,
  icons: [
    IconModel(display: 'aeuro02Icon', path: MoneyConstant.aeuro02Icon),
    IconModel(display: 'aeuro03Icon', path: MoneyConstant.aeuro03Icon),
    IconModel(display: 'aeuro04Icon', path: MoneyConstant.aeuro04Icon),
    IconModel(display: 'aeuro05Icon', path: MoneyConstant.aeuro05Icon),
    IconModel(display: 'aeuro06Icon', path: MoneyConstant.aeuro06Icon),
    IconModel(display: 'aeuro07Icon', path: MoneyConstant.aeuro07Icon),
    IconModel(display: 'aeuro08Icon', path: MoneyConstant.aeuro08Icon),
    IconModel(display: 'aeuro09Icon', path: MoneyConstant.aeuro09Icon),
    IconModel(display: 'aeuro10Icon', path: MoneyConstant.aeuro10Icon),
    IconModel(display: 'astat01Icon', path: MoneyConstant.astat01Icon),
    IconModel(display: 'astat02Icon', path: MoneyConstant.astat02Icon),
    IconModel(display: 'astat03Icon', path: MoneyConstant.astat03Icon),
    IconModel(display: 'bank01Icon', path: MoneyConstant.bank01Icon),
    IconModel(display: 'bank02Icon', path: MoneyConstant.bank02Icon),
    IconModel(display: 'dolar01Icon', path: MoneyConstant.dolar01Icon),
    IconModel(display: 'dolar02Icon', path: MoneyConstant.dolar02Icon),
    IconModel(display: 'dolar03Icon', path: MoneyConstant.dolar03Icon),
    IconModel(display: 'dolar04Icon', path: MoneyConstant.dolar04Icon),
    IconModel(display: 'dolar05Icon', path: MoneyConstant.dolar05Icon),
    IconModel(display: 'dolar06Icon', path: MoneyConstant.dolar06Icon),
    IconModel(display: 'dolar07Icon', path: MoneyConstant.dolar07Icon),
    IconModel(display: 'dolar08Icon', path: MoneyConstant.dolar08Icon),
    IconModel(display: 'dolar09Icon', path: MoneyConstant.dolar09Icon),
    IconModel(display: 'dolar10Icon', path: MoneyConstant.dolar10Icon),
    IconModel(display: 'dolar13Icon', path: MoneyConstant.dolar13Icon),
    IconModel(display: 'globalIcon', path: MoneyConstant.globalIcon),
    IconModel(display: 'money01Icon', path: MoneyConstant.money01Icon),
    IconModel(display: 'money02Icon', path: MoneyConstant.money02Icon),
    IconModel(display: 'money04Icon', path: MoneyConstant.money04Icon),
    IconModel(display: 'money05Icon', path: MoneyConstant.money05Icon),
    IconModel(display: 'money06Icon', path: MoneyConstant.money06Icon),
  ],
);
