part of 'icon_constant.dart';

const IconCategoryModel _$numbersCategoryIcons = IconCategoryModel(
  display: 'numbers',
  path: NumbersConstant.categoryIcon,
  position: NumbersConstant.categoryNo,
  icons: [
    IconModel(display: 'a0Icon', path: NumbersConstant.a0Icon),
    IconModel(display: 'a1Icon', path: NumbersConstant.a1Icon),
    IconModel(display: 'a2Icon', path: NumbersConstant.a2Icon),
    IconModel(display: 'a3Icon', path: NumbersConstant.a3Icon),
    IconModel(display: 'a4Icon', path: NumbersConstant.a4Icon),
    IconModel(display: 'a5Icon', path: NumbersConstant.a5Icon),
    IconModel(display: 'a6Icon', path: NumbersConstant.a6Icon),
    IconModel(display: 'a7Icon', path: NumbersConstant.a7Icon),
    IconModel(display: 'a8Icon', path: NumbersConstant.a8Icon),
    IconModel(display: 'a9Icon', path: NumbersConstant.a9Icon),
    IconModel(display: 'as01Icon', path: NumbersConstant.as01Icon),
    IconModel(display: 'as02Icon', path: NumbersConstant.as02Icon),
    IconModel(display: 'as03Icon', path: NumbersConstant.as03Icon),
    IconModel(display: 'as03aIcon', path: NumbersConstant.as03aIcon),
    IconModel(display: 'as03bIcon', path: NumbersConstant.as03bIcon),
    IconModel(display: 'as04Icon', path: NumbersConstant.as04Icon),
    IconModel(display: 'as05Icon', path: NumbersConstant.as05Icon),
    IconModel(display: 'as06Icon', path: NumbersConstant.as06Icon),
    IconModel(display: 'as07Icon', path: NumbersConstant.as07Icon),
    IconModel(display: 'as08Icon', path: NumbersConstant.as08Icon),
    IconModel(display: 'as09Icon', path: NumbersConstant.as09Icon),
    IconModel(display: 'as10Icon', path: NumbersConstant.as10Icon),
    IconModel(display: 'b0Icon', path: NumbersConstant.b0Icon),
    IconModel(display: 'b1Icon', path: NumbersConstant.b1Icon),
    IconModel(display: 'b2Icon', path: NumbersConstant.b2Icon),
    IconModel(display: 'b3Icon', path: NumbersConstant.b3Icon),
    IconModel(display: 'b4Icon', path: NumbersConstant.b4Icon),
    IconModel(display: 'b5Icon', path: NumbersConstant.b5Icon),
    IconModel(display: 'b6Icon', path: NumbersConstant.b6Icon),
    IconModel(display: 'b7Icon', path: NumbersConstant.b7Icon),
    IconModel(display: 'b8Icon', path: NumbersConstant.b8Icon),
    IconModel(display: 'b9Icon', path: NumbersConstant.b9Icon),
    IconModel(display: 'bs01Icon', path: NumbersConstant.bs01Icon),
    IconModel(display: 'bs02Icon', path: NumbersConstant.bs02Icon),
    IconModel(display: 'bs03Icon', path: NumbersConstant.bs03Icon),
    IconModel(display: 'bs04Icon', path: NumbersConstant.bs04Icon),
    IconModel(display: 'bs05Icon', path: NumbersConstant.bs05Icon),
    IconModel(display: 'bs06Icon', path: NumbersConstant.bs06Icon),
    IconModel(display: 'bs07Icon', path: NumbersConstant.bs07Icon),
    IconModel(display: 'bs08Icon', path: NumbersConstant.bs08Icon),
    IconModel(display: 'bs09Icon', path: NumbersConstant.bs09Icon),
    IconModel(display: 'bs10Icon', path: NumbersConstant.bs10Icon),
    IconModel(display: 'bs11Icon', path: NumbersConstant.bs11Icon),
    IconModel(display: 'bs12Icon', path: NumbersConstant.bs12Icon),
    IconModel(display: 'bIcon', path: NumbersConstant.bIcon),
  ],
);
