part of 'icon_constant.dart';

const IconCategoryModel _$physicsCategoryIcons = IconCategoryModel(
  display: 'physics',
  path: PhysicsConstant.categoryIcon,
  position: PhysicsConstant.categoryNo,
  icons: [
    IconModel(display: 'electricCircuitIcon', path: PhysicsConstant.electricCircuitIcon),
    IconModel(display: 'experimentIcon', path: PhysicsConstant.experimentIcon),
    IconModel(display: 'frictionIcon', path: PhysicsConstant.frictionIcon),
    IconModel(display: 'gravityIcon', path: PhysicsConstant.gravityIcon),
    IconModel(display: 'hydraulicIcon', path: PhysicsConstant.hydraulicIcon),
    IconModel(display: 'magnetIcon', path: PhysicsConstant.magnetIcon),
    IconModel(display: 'magneticIcon', path: PhysicsConstant.magneticIcon),
    IconModel(display: 'magnetsIcon', path: PhysicsConstant.magnetsIcon),
    IconModel(display: 'pendulumIcon', path: PhysicsConstant.pendulumIcon),
    IconModel(display: 'physicsIcon', path: PhysicsConstant.physicsIcon),
    IconModel(display: 'physics2Icon', path: PhysicsConstant.physics2Icon),
    IconModel(display: 'physics3Icon', path: PhysicsConstant.physics3Icon),
    IconModel(display: 'pulleyIcon', path: PhysicsConstant.pulleyIcon),
    IconModel(display: 'theoryIcon', path: PhysicsConstant.theoryIcon),
    IconModel(display: 'visionIcon', path: PhysicsConstant.visionIcon),
    IconModel(display: 'waveIcon', path: PhysicsConstant.waveIcon),
    IconModel(display: 'ww000threearrowsIcon', path: PhysicsConstant.ww000threearrowsIcon),
    IconModel(display: 'ww001dimensions2Icon', path: PhysicsConstant.ww001dimensions2Icon),
    IconModel(display: 'ww002dimensionsIcon', path: PhysicsConstant.ww002dimensionsIcon),
    IconModel(display: 'ww004dimensionIcon', path: PhysicsConstant.ww004dimensionIcon),
    IconModel(display: 'ww004thoughtIcon', path: PhysicsConstant.ww004thoughtIcon),
    IconModel(display: 'ww005dimensions1Icon', path: PhysicsConstant.ww005dimensions1Icon),
    IconModel(display: 'ww005scalescreenIcon', path: PhysicsConstant.ww005scalescreenIcon),
    IconModel(display: 'ww006dimension2Icon', path: PhysicsConstant.ww006dimension2Icon),
    IconModel(display: 'ww006dimension3Icon', path: PhysicsConstant.ww006dimension3Icon),
    IconModel(display: 'ww007dimension1Icon', path: PhysicsConstant.ww007dimension1Icon),
    IconModel(display: 'ww008measureIcon', path: PhysicsConstant.ww008measureIcon),
    IconModel(display: 'ww010squaremeasumentIcon', path: PhysicsConstant.ww010squaremeasumentIcon),
    IconModel(display: 'ww011solarpanelIcon', path: PhysicsConstant.ww011solarpanelIcon),
    IconModel(display: 'ww013dimensions3Icon', path: PhysicsConstant.ww013dimensions3Icon),
    IconModel(display: 'ww014sphereIcon', path: PhysicsConstant.ww014sphereIcon),
    IconModel(display: 'ww016measure1Icon', path: PhysicsConstant.ww016measure1Icon),
    IconModel(display: 'ww017dimension4Icon', path: PhysicsConstant.ww017dimension4Icon),
  ],
);
