
part of 'icon_constant.dart';

const IconCategoryModel _$plantCategoryIcons = IconCategoryModel(
  display: 'human',
  path: PlantConstant.categoryIcon,
  position: PlantConstant.categoryNo,
  icons: [
    IconModel(display: 'anemoneIcon', path: PlantConstant.anemoneIcon),
    IconModel(display: 'appletreeIcon', path: PlantConstant.appletreeIcon),
    IconModel(display: 'branchleavesIcon', path: PlantConstant.branchleavesIcon),
    IconModel(display: 'burningIcon', path: PlantConstant.burningIcon),
    IconModel(display: 'cherryblossomIcon', path: PlantConstant.cherryblossomIcon),
    IconModel(display: 'elmIcon', path: PlantConstant.elmIcon),
    IconModel(display: 'flowerIcon', path: PlantConstant.flowerIcon),
    IconModel(display: 'flower2Icon', path: PlantConstant.flower2Icon),
    IconModel(display: 'leafIcon', path: PlantConstant.leafIcon),
    IconModel(display: 'leavesIcon', path: PlantConstant.leavesIcon),
    IconModel(display: 'lotusIcon', path: PlantConstant.lotusIcon),
    IconModel(display: 'lotusflowerIcon', path: PlantConstant.lotusflowerIcon),
    IconModel(display: 'olivesIcon', path: PlantConstant.olivesIcon),
    IconModel(display: 'olivetreeIcon', path: PlantConstant.olivetreeIcon),
    IconModel(display: 'pineconeIcon', path: PlantConstant.pineconeIcon),
    IconModel(display: 'planttreeIcon', path: PlantConstant.planttreeIcon),
    IconModel(display: 'roseIcon', path: PlantConstant.roseIcon),
    IconModel(display: 'rose2Icon', path: PlantConstant.rose2Icon),
    IconModel(display: 'rose3Icon', path: PlantConstant.rose3Icon),
    IconModel(display: 'spiderplantIcon', path: PlantConstant.spiderplantIcon),
    IconModel(display: 'treeIcon', path: PlantConstant.treeIcon),
    IconModel(display: 'tree01Icon', path: PlantConstant.tree01Icon),
    IconModel(display: 'tree02Icon', path: PlantConstant.tree02Icon),
    IconModel(display: 'tree03Icon', path: PlantConstant.tree03Icon),
    IconModel(display: 'tree04Icon', path: PlantConstant.tree04Icon),
    IconModel(display: 'tree05Icon', path: PlantConstant.tree05Icon),
    IconModel(display: 'tree06Icon', path: PlantConstant.tree06Icon),
    IconModel(display: 'tree07Icon', path: PlantConstant.tree07Icon),
    IconModel(display: 'tree09Icon', path: PlantConstant.tree09Icon),
    IconModel(display: 'tree2Icon', path: PlantConstant.tree2Icon),
    IconModel(display: 'treeo8Icon', path: PlantConstant.treeo8Icon),
    IconModel(display: 'wood2Icon', path: PlantConstant.wood2Icon),
    IconModel(display: 'wood3Icon', path: PlantConstant.wood3Icon),
    IconModel(display: 'woodcuttingIcon', path: PlantConstant.woodcuttingIcon),

  ],
);