part of 'icon_constant.dart';

const IconCategoryModel _$religionCategoryIcons = IconCategoryModel(
  display: 'religion',
  path: ReligionConstant.categoryIcon,
  position: ReligionConstant.categoryNo,
  icons: [
    IconModel(display: 'caodaiIcon', path: ReligionConstant.caodaiIcon),
    IconModel(display: 'cuauhtliIcon', path: ReligionConstant.cuauhtliIcon),
    IconModel(display: 'ganeshaIcon', path: ReligionConstant.ganeshaIcon),
    IconModel(display: 'ganesha2Icon', path: ReligionConstant.ganesha2Icon),
    IconModel(display: 'godIcon', path: ReligionConstant.godIcon),
    IconModel(display: 'god2Icon', path: ReligionConstant.god2Icon),
    IconModel(display: 'god3Icon', path: ReligionConstant.god3Icon),
    IconModel(display: 'god4Icon', path: ReligionConstant.god4Icon),
    IconModel(display: 'god5Icon', path: ReligionConstant.god5Icon),
    IconModel(display: 'godofwealthIcon', path: ReligionConstant.godofwealthIcon),
    IconModel(display: 'godofwealth2Icon', path: ReligionConstant.godofwealth2Icon),
    IconModel(display: 'goo01Icon', path: ReligionConstant.goo01Icon),
    IconModel(display: 'good02Icon', path: ReligionConstant.good02Icon),
    IconModel(display: 'good03Icon', path: ReligionConstant.good03Icon),
    IconModel(display: 'good04Icon', path: ReligionConstant.good04Icon),
    IconModel(display: 'good05Icon', path: ReligionConstant.good05Icon),
    IconModel(display: 'good06Icon', path: ReligionConstant.good06Icon),
    IconModel(display: 'good07Icon', path: ReligionConstant.good07Icon),
    IconModel(display: 'good08Icon', path: ReligionConstant.good08Icon),
    IconModel(display: 'good09Icon', path: ReligionConstant.good09Icon),
    IconModel(display: 'good10Icon', path: ReligionConstant.good10Icon),
    IconModel(display: 'good11Icon', path: ReligionConstant.good11Icon),
    IconModel(display: 'good12Icon', path: ReligionConstant.good12Icon),
    IconModel(display: 'harpIcon', path: ReligionConstant.harpIcon),
    IconModel(display: 'hermesIcon', path: ReligionConstant.hermesIcon),
    IconModel(display: 'orpheusIcon', path: ReligionConstant.orpheusIcon),
    IconModel(display: 'poseidonIcon', path: ReligionConstant.poseidonIcon),
    IconModel(display: 'prayerIcon', path: ReligionConstant.prayerIcon),
    IconModel(display: 'sunIcon', path: ReligionConstant.sunIcon),
    IconModel(display: 'worldIcon', path: ReligionConstant.worldIcon),
    IconModel(display: 'zeusIcon', path: ReligionConstant.zeusIcon),
  ],
);
