part of 'icon_constant.dart';

const IconCategoryModel _$symbolsCategoryIcons = IconCategoryModel(
  display: 'symbols',
  path: SymbolsConstant.categoryIcon,
  position: SymbolsConstant.categoryNo,
  icons: [
    IconModel(display: 'abullet13Icon', path: SymbolsConstant.abullet13Icon),
    IconModel(display: 'abullet14Icon', path: SymbolsConstant.abullet14Icon),
    IconModel(display: 'blurIcon', path: SymbolsConstant.blurIcon),
    IconModel(display: 'bsymbol01Icon', path: SymbolsConstant.bsymbol01Icon),
    IconModel(display: 'bsymbol02Icon', path: SymbolsConstant.bsymbol02Icon),
    IconModel(display: 'caduceussymbolIcon', path: SymbolsConstant.caduceussymbolIcon),
    IconModel(display: 'climbingIcon', path: SymbolsConstant.climbingIcon),
    IconModel(display: 'copyrightIcon', path: SymbolsConstant.copyrightIcon),
    IconModel(display: 'emailIcon', path: SymbolsConstant.emailIcon),
    IconModel(display: 'endlessknotIcon', path: SymbolsConstant.endlessknotIcon),
    IconModel(display: 'eternityIcon', path: SymbolsConstant.eternityIcon),
    IconModel(display: 'femenineIcon', path: SymbolsConstant.femenineIcon),
    IconModel(display: 'finishIcon', path: SymbolsConstant.finishIcon),
    IconModel(display: 'finishflag2Icon', path: SymbolsConstant.finishflag2Icon),
    IconModel(display: 'flag02Icon', path: SymbolsConstant.flag02Icon),
    IconModel(display: 'flag02bIcon', path: SymbolsConstant.flag02bIcon),
    IconModel(display: 'flag03Icon', path: SymbolsConstant.flag03Icon),
    IconModel(display: 'flag04Icon', path: SymbolsConstant.flag04Icon),
    IconModel(display: 'flag2Icon', path: SymbolsConstant.flag2Icon),
    IconModel(display: 'flag3Icon', path: SymbolsConstant.flag3Icon),
    IconModel(display: 'functionIcon', path: SymbolsConstant.functionIcon),
    IconModel(display: 'islamIcon', path: SymbolsConstant.islamIcon),
    IconModel(display: 'mathematicsIcon', path: SymbolsConstant.mathematicsIcon),
    IconModel(display: 'missionIcon', path: SymbolsConstant.missionIcon),
    IconModel(display: 'monkeyIcon', path: SymbolsConstant.monkeyIcon),
    IconModel(display: 'musicalsignformusicclassIcon', path: SymbolsConstant.musicalsignformusicclassIcon),
    IconModel(display: 'paragraphIcon', path: SymbolsConstant.paragraphIcon),
    IconModel(display: 'peaceIcon', path: SymbolsConstant.peaceIcon),
    IconModel(display: 'rupeeIcon', path: SymbolsConstant.rupeeIcon),
    IconModel(display: 'ssymbol002Icon', path: SymbolsConstant.ssymbol002Icon),
    IconModel(display: 'ssymbol003Icon', path: SymbolsConstant.ssymbol003Icon),
    IconModel(display: 'ssymbol004Icon', path: SymbolsConstant.ssymbol004Icon),
    IconModel(display: 'symbolIcon', path: SymbolsConstant.symbolIcon),
    IconModel(display: 'triangleIcon', path: SymbolsConstant.triangleIcon),
  ],
);
