part of 'icon_constant.dart';

const IconCategoryModel _$technologyCategoryIcons = IconCategoryModel(
  display: 'technology',
  path: TechnologyConstant.categoryIcon,
  position: TechnologyConstant.categoryNo,
  icons: [
    IconModel(display: 'apiIcon', path: TechnologyConstant.apiIcon),
    IconModel(display: 'artificialintelligenceIcon', path: TechnologyConstant.artificialintelligenceIcon),
    IconModel(display: 'artificialintelligence2Icon', path: TechnologyConstant.artificialintelligence2Icon),
    IconModel(display: 'chipIcon', path: TechnologyConstant.chipIcon),
    IconModel(display: 'cloudIcon', path: TechnologyConstant.cloudIcon),
    IconModel(display: 'computerIcon', path: TechnologyConstant.computerIcon),
    IconModel(display: 'cpuIcon', path: TechnologyConstant.cpuIcon),
    IconModel(display: 'cyborgIcon', path: TechnologyConstant.cyborgIcon),
    IconModel(display: 'energy01Icon', path: TechnologyConstant.energy01Icon),
    IconModel(display: 'energy02Icon', path: TechnologyConstant.energy02Icon),
    IconModel(display: 'energy03Icon', path: TechnologyConstant.energy03Icon),
    IconModel(display: 'energy04Icon', path: TechnologyConstant.energy04Icon),
    IconModel(display: 'energy05Icon', path: TechnologyConstant.energy05Icon),
    IconModel(display: 'energy06Icon', path: TechnologyConstant.energy06Icon),
    IconModel(display: 'energy07Icon', path: TechnologyConstant.energy07Icon),
    IconModel(display: 'energy08Icon', path: TechnologyConstant.energy08Icon),
    IconModel(display: 'fieldIcon', path: TechnologyConstant.fieldIcon),
    IconModel(display: 'globaldistributionIcon', path: TechnologyConstant.globaldistributionIcon),
    IconModel(display: 'greentechnologyIcon', path: TechnologyConstant.greentechnologyIcon),
    IconModel(display: 'heartIcon', path: TechnologyConstant.heartIcon),
    IconModel(display: 'innovationIcon', path: TechnologyConstant.innovationIcon),
    IconModel(display: 'nanotechnologyIcon', path: TechnologyConstant.nanotechnologyIcon),
    IconModel(display: 'nanotechnology2Icon', path: TechnologyConstant.nanotechnology2Icon),
    IconModel(display: 'projectmanagementIcon', path: TechnologyConstant.projectmanagementIcon),
    IconModel(display: 'smartfarmIcon', path: TechnologyConstant.smartfarmIcon),
    IconModel(display: 'technologyIcon', path: TechnologyConstant.technologyIcon),
    IconModel(display: 'touchIcon', path: TechnologyConstant.touchIcon),
  ],
);
