part of 'icon_constant.dart';

const IconCategoryModel _$warCategoryIcons = IconCategoryModel(
  display: 'war',
  path: WarConstant.categoryIcon,
  position: WarConstant.categoryNo,
  icons: [
    IconModel(display: 'armorIcon', path: WarConstant.armorIcon),
    IconModel(display: 'armor2Icon', path: WarConstant.armor2Icon),
    IconModel(display: 'armor3Icon', path: WarConstant.armor3Icon),
    IconModel(display: 'armor4Icon', path: WarConstant.armor4Icon),
    IconModel(display: 'axeIcon', path: WarConstant.axeIcon),
    IconModel(display: 'axe2Icon', path: WarConstant.axe2Icon),
    IconModel(display: 'battleIcon', path: WarConstant.battleIcon),
    IconModel(display: 'battle2Icon', path: WarConstant.battle2Icon),
    IconModel(display: 'battleAxeIcon', path: WarConstant.battleAxeIcon),
    IconModel(display: 'battleShieldIcon', path: WarConstant.battleShieldIcon),
    IconModel(display: 'battleShield2Icon', path: WarConstant.battleShield2Icon),
    IconModel(display: 'boxingIcon', path: WarConstant.boxingIcon),
    IconModel(display: 'catapultIcon', path: WarConstant.catapultIcon),
    IconModel(display: 'crossedIcon', path: WarConstant.crossedIcon),
    IconModel(display: 'fireIcon', path: WarConstant.fireIcon),
    IconModel(display: 'helmetIcon', path: WarConstant.helmetIcon),
    IconModel(display: 'helmet2Icon', path: WarConstant.helmet2Icon),
    IconModel(display: 'helmet3Icon', path: WarConstant.helmet3Icon),
    IconModel(display: 'helmet4Icon', path: WarConstant.helmet4Icon),
    IconModel(display: 'helmet5Icon', path: WarConstant.helmet5Icon),
    IconModel(display: 'helmet6Icon', path: WarConstant.helmet6Icon),
    IconModel(display: 'helmet7Icon', path: WarConstant.helmet7Icon),
    IconModel(display: 'historyIcon', path: WarConstant.historyIcon),
    IconModel(display: 'shieldIcon', path: WarConstant.shieldIcon),
    IconModel(display: 'shield2Icon', path: WarConstant.shield2Icon),
    IconModel(display: 'spearIcon', path: WarConstant.spearIcon),
    IconModel(display: 'swordsIcon', path: WarConstant.swordsIcon),
    IconModel(display: 'trojanHorseIcon', path: WarConstant.trojanHorseIcon),
  ],
);
