part of 'icon_constant.dart';

const IconCategoryModel _$workerCategoryIcons = IconCategoryModel(
  display: 'worker',
  path: WorkerConstant.categoryIcon,
  position: WorkerConstant.categoryNo,
  icons: [
    IconModel(display: '001workerIcon', path: WorkerConstant.worker001workerIcon),
    IconModel(display: '002teamIcon', path: WorkerConstant.worker002teamIcon),
    IconModel(display: '003trolleyIcon', path: WorkerConstant.worker003trolleyIcon),
    IconModel(display: '005worker2Icon', path: WorkerConstant.worker005worker2Icon),
    IconModel(display: '006waiterIcon', path: WorkerConstant.worker006waiterIcon),
    IconModel(display: '007worker3Icon', path: WorkerConstant.worker007worker3Icon),
    IconModel(display: '008hardhatIcon', path: WorkerConstant.worker008hardhatIcon),
    IconModel(display: '009weldingIcon', path: WorkerConstant.worker009weldingIcon),
    IconModel(display: '010workspaceIcon', path: WorkerConstant.worker010workspaceIcon),
    IconModel(display: '011mechanicIcon', path: WorkerConstant.worker011mechanicIcon),
    IconModel(display: '012engineerIcon', path: WorkerConstant.worker012engineerIcon),
    IconModel(display: '013engineer1Icon', path: WorkerConstant.worker013engineer1Icon),
    IconModel(display: '014hammerIcon', path: WorkerConstant.worker014hammerIcon),
    IconModel(display: '015protestIcon', path: WorkerConstant.worker015protestIcon),
    IconModel(display: '016masonryIcon', path: WorkerConstant.worker016masonryIcon),
    IconModel(display: '017cofounderIcon', path: WorkerConstant.worker017cofounderIcon),
    IconModel(display: '018constructionIcon', path: WorkerConstant.worker018constructionIcon),
    IconModel(display: '019diggingIcon', path: WorkerConstant.worker019diggingIcon),
    IconModel(display: '020employeeIcon', path: WorkerConstant.worker020employeeIcon),
    IconModel(display: '021bestemployeeIcon', path: WorkerConstant.worker021bestemployeeIcon),
    IconModel(display: '022labtechnicianIcon', path: WorkerConstant.worker022labtechnicianIcon),
    IconModel(display: '023farmerIcon', path: WorkerConstant.worker023farmerIcon),
    IconModel(display: '024vineyardIcon', path: WorkerConstant.worker024vineyardIcon),
    IconModel(display: '025tractorIcon', path: WorkerConstant.worker025tractorIcon),
    IconModel(display: '026farmIcon', path: WorkerConstant.worker026farmIcon),
    IconModel(display: '027shovelsIcon', path: WorkerConstant.worker027shovelsIcon),
    IconModel(display: '028farmer1Icon', path: WorkerConstant.worker028farmer1Icon),
    IconModel(display: '029standIcon', path: WorkerConstant.worker029standIcon),
    IconModel(display: '030agricultureIcon', path: WorkerConstant.worker030agricultureIcon),
  ],
);
