name: notebars
description: Notebars studying & notes taking application

publish_to: 'none'

version: 1.0.1+3

environment:
  sdk: ">=2.17.3 <3.0.0"

dependencies:
  badges: ^2.0.3
  collection: ^1.16.0
  encrypt: ^5.0.1
  event_dart: ^2.0.1
  flutter_colorpicker: ^1.0.3
  flutter_launcher_icons: ^0.9.3
  flutter_slidable: ^2.0.0
  flutter_speed_dial: ^6.0.0
  flutter_staggered_animations: ^1.0.0
  flutter_svg: ^1.1.1+1
  get_it: ^7.2.0
  google_sign_in: ^5.4.0
  googleapis: ^9.1.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  html: ^0.15.0
  http: ^0.13.4
  icons_plus: ^2.0.1
  image: ^3.2.0
  image_picker: ^0.8.5+3
  in_app_notification: ^1.1.2
  intl: ^0.17.0
  path_provider: ^2.0.11
  popover: 0.2.6+3
  reorderables: ^0.5.0
  test: ^1.16.0
  transparent_image: ^2.0.0
  uuid: ^3.0.6
  aneya_appstyle: ^1.0.0
  basic_utils: ^3.4.0
  mask_text_input_formatter: ^1.0.6

  aneya_core:
    path: packages/aneya/core
  aneya_app_flutter:
    path: packages/aneya/app_flutter
  aneya_auth:
    path: packages/aneya/auth
  aneya_json:
    path: packages/aneya/json
  aneya_responsive:
    path: packages/aneya/responsive

  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.5
  flutter_native_splash: ^2.2.10+1
  get: ^4.6.5
  connectivity_plus: ^2.3.9
  card_swiper: ^2.0.4
  url_launcher: ^6.1.7
  flutter_signin_button: ^2.0.0
  dio: ^4.0.6
  flutterfire: ^0.0.1
  firedart: ^0.9.0+1
  googleapis_auth: ^1.3.1
  window_to_front: ^0.0.3
  oauth2: ^2.0.1
  flutter_secure_storage: ^7.0.1
  jwt_decode: ^0.3.1
  flutter_web_auth: ^0.5.0
  google_sign_in_dartio: ^0.2.2
  file_picker_cross: ^4.4.2

dev_dependencies:
  flutter_lints: any
  flutter_test:
    sdk: flutter

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/launcher-icon.png"

flutter:

  uses-material-design: true

  assets:
    - cfg/config.json
    - logo-icon.png
    - logo-with-text.svg
    - logo-with-text.png
    - assets/
    - assets/json/
    - assets/illustrations/
    - assets/svg/
    - assets/svg/notes/
    - assets/svg/notes/bullets/
    - assets/svg/notes/numbers/
    - assets/svg/notes/human/
    - assets/svg/notes/education/
    - assets/svg/notes/worker/
    - assets/svg/notes/law/
    - assets/svg/notes/animal/
    - assets/svg/notes/plant/
    - assets/svg/notes/religion/
    - assets/svg/notes/history/
    - assets/svg/notes/reign/
    - assets/svg/notes/alien/
    - assets/svg/notes/biology/
    - assets/svg/notes/boat/
    - assets/svg/notes/car/
    - assets/svg/notes/chemistry/
    - assets/svg/notes/egypt/
    - assets/svg/notes/parts/
    - assets/svg/notes/physics/
    - assets/svg/notes/polemic/
    - assets/svg/notes/symbols/
    - assets/svg/notes/technology/
    - assets/svg/notes/war/
    - assets/svg/notes/money/

  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Bold.ttf
          weight: 600
        - asset: assets/fonts/Roboto-Medium.ttf
          weight: 400
        - asset: assets/fonts/Roboto-Regular.ttf
          weight: 500
